#!/usr/bin/env sh
. "$(dirname "$0")/h"

# Run Prettier on frontend
cd ../../source-code/frontend && npx prettier --check . || exit 1

# Run frontend tests
npm test || exit 1

# Run backend Python syntax check
cd ../backend || exit 1
find . -name "*.py" -exec python -m py_compile {} + || exit 1

# Success message
printf '\033[1mThank you for contributing to OnlyLinks!\033[0m\n'